version: '2'
services:
  mocker:
    image: stutzlab/homie-esp8266-config-emulator:0.1.0
    build: ./src
    ports:
      - 5000:5000
    environment:
      - "DEBUG=info,fine"
      - "FAILURE_RATE=.1"
